export const LOGIN_API = 'auth/login'
export const BRAND_API = 'brands'
export const CATEGORY_API = 'categories'
export const PRODUCT_API = 'products'
export const PRESCRIPTION_API = 'prescription'
export const PRESCRIPTION_STATUS_API = 'prescription/order-status'
export const PRESCRIPTION_ORDER_API = 'prescription/order'
export const COUPON_API = 'coupons'
