export const LOGIN_UI = '/'
export const ADMIN_HOME_UI = '/admin/'
export const ADMIN_COMPANIES_UI = '/admin/companies'
export const ADMIN_CATEGORIES_UI = '/admin/categories'
export const ADMIN_PRODUCTS_UI = '/admin/products'
export const ADMIN_ORDERS_UI = '/admin/orders'
export const ADMIN_USERS_UI = '/admin/users'
export const ADMIN_PAYMENTS_UI = '/admin/payments'
export const ADMIN_SETTINGS_UI = '/admin/settings'

